---
 # This Playbook installs iostats and runs it
 
- hosts: tag_iostats_true
  remote_user: ubuntu
  sudo: true
  gather_facts: yes
  vars_files:
  # Importing OS related variables, e.g., "group_vars/ubuntu".
  - "group_vars/{{ ansible_distribution }}"
  # Importing cloud provider related variables, e.g., "group_vars/aws".
  - "group_vars/aws"
  roles:
  - role: iostats
